-- Create the assets storage bucket for logo and favicon uploads
-- This bucket will store uploaded files like logos, favicons, and other assets
--
-- IMPORTANT: This script only creates the bucket. Storage policies are automatically
-- managed by Supabase when you create a bucket through the dashboard UI.
--
-- To create the bucket:
-- 1. Go to Supabase Dashboard → Storage
-- 2. Click "Create bucket"
-- 3. Name: "assets"
-- 4. Check "Public bucket"
-- 5. Click "Create bucket"
--
-- The bucket will be created with default policies that allow:
-- - Authenticated users to upload files
-- - Public access to view files (since it's public)

-- Alternative: If you have admin permissions, you can run this SQL:
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('assets', 'assets', true)
-- ON CONFLICT (id) DO NOTHING;